### ISSUE TITLE
question about your program

### ISSUE THREAD

**Issue by zjin-lcf** [develancer/amd-opencl-test-case#1]
Can I port your program using other languages (hip, cuda) after some license is added ?

Thanks

**Comment by develancer** [comment]
Personally, I don't mind. However, I'm not sure if I can add any license, since part of this code is based on [bip39-solver](https://github.com/johncantrell97/bip39-solver-gpu) which does not specify any license whatsoever. However, the main part of the codebase is taken from [secp256k1](https://github.com/bitcoin-core/secp256k1) which has been published on the MIT License, so I think you can assume the same license for the entire project.

**Comment by zjin-lcf** [comment]
Okay.
